use std::fs;use std::time::{SystemTime,UNIX_EPOCH};
use mahayana_host_runtime::workflows::stat_keyed_parse_cache::mtime_tick_could_still_hide_an_edit;
use mahayana_host_runtime::workflows::workflow_library::{GlobalWorkflowLibrary,LEGACY_WORKFLOW_FILENAME,WORKFLOW_FILENAME,WorkflowSpec,WorkflowTrigger,parse_workflow_file,serialize_workflow_file};
use mahayana_host_runtime::workflows::workflow_store::{FileWorkflowStore,agent_has_workflows};
fn root(label:&str)->std::path::PathBuf{let n=SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos();std::env::temp_dir().join(format!("fabushi-workflow-{label}-{}-{n}",std::process::id()))}
#[test]fn frontmatter_round_trip(){let raw="---\nname: \"Deploy helper\"\ndescription: \"desc\"\nmetadata:\n  source: \"https://example.test/skill.md\"\ntrigger:\n  schedule: \"0 9 * * 1-5\"\n  enabled: false\ncustom: true\n---\n# Body\nDo it.\n";let p=parse_workflow_file(raw).unwrap();assert_eq!(p.spec.name,"Deploy helper");assert_eq!(p.spec.source_ref.as_deref(),Some("https://example.test/skill.md"));assert_eq!(p.spec.trigger.as_ref().unwrap().schedule,"0 9 * * 1-5");assert!(!p.spec.trigger.as_ref().unwrap().is_enabled);let encoded=serialize_workflow_file(&p.spec,&p.data);assert!(encoded.contains("custom: true"));assert!(encoded.contains("# Body"));}
#[test]fn global_library_crud_and_legacy_rename(){let root=root("library");let library=GlobalWorkflowLibrary::new(&root);let spec=WorkflowSpec{name:"Review PR".into(),description:"review".into(),body:"Read the diff".into(),trigger:None,source_ref:None};let first=library.create(&spec).unwrap().unwrap();assert_eq!(first.id,"review-pr");let second=library.create(&spec).unwrap().unwrap();assert_eq!(second.id,"review-pr-2");fs::write(library.folder(&first.id).join("helper.sh"),"echo hi").unwrap();assert_eq!(library.get(&first.id).unwrap().helper_scripts,vec!["helper.sh"]);assert!(library.remove(&second.id).unwrap());let legacy=library.folder("legacy");fs::create_dir_all(&legacy).unwrap();fs::write(legacy.join(LEGACY_WORKFLOW_FILENAME),"---\nname: Legacy\n---\nbody\n").unwrap();library.rename_legacy_recipe_files();assert!(legacy.join(WORKFLOW_FILENAME).is_file());let _=fs::remove_dir_all(root);}
#[test]fn store_projects_automation_and_migrates_legacy(){let root=root("store");let agent=root.join("agents/a");let global=root.join("workflows");let legacy=agent.join("workflows/old");fs::create_dir_all(&legacy).unwrap();fs::write(legacy.join(LEGACY_WORKFLOW_FILENAME),"---\nname: Old\n---\nLegacy body\n").unwrap();assert!(agent_has_workflows(&agent));let store=FileWorkflowStore::new(&agent,&global);assert!(global.join("old/SKILL.md").is_file());let created=store.create(&WorkflowSpec{name:"Daily".into(),description:String::new(),body:"Do daily".into(),trigger:Some(WorkflowTrigger{schedule:"0 9 * * 1-5".into(),is_enabled:true}),source_ref:None}).unwrap().unwrap();assert_eq!(created.source,"automation");assert!(store.list_all().iter().any(|w|w.id==created.id));let _=fs::remove_dir_all(root);}
#[test]fn racy_mtime_boundary(){assert!(mtime_tick_could_still_hide_an_edit(9_000,10_999));assert!(!mtime_tick_could_still_hide_an_edit(9_000,11_000));}
