use std::fs;use std::path::{Path,PathBuf};use std::sync::Arc;use std::time::{SystemTime,UNIX_EPOCH};
use serde_json::json;
use crate::agents::agent_workflow_enablement::AgentWorkflowEnablement;
use crate::automations::automation::{AutomationRecord,AutomationSpec};
use crate::automations::automation_store::{FileAutomationStore,UserTimeZoneResolver,get_agent_automations_dir};
use super::workflow_library::{GlobalWorkflowLibrary,GlobalWorkflowRecord,LEGACY_WORKFLOW_FILENAME,WorkflowSpec,WorkflowTrigger,clamp_workflow_body,clamp_workflow_name,parse_workflow_file};
pub const LEGACY_WORKFLOWS_DIRNAME:&str="workflows";
#[derive(Debug,Clone,PartialEq)]pub struct WorkflowRecord{pub id:String,pub name:String,pub description:String,pub body:String,pub trigger:Option<WorkflowTrigger>,pub source:String,pub source_ref:Option<String>,pub is_enabled_for_agent:bool,pub created_at:f64,pub last_run_at:Option<f64>,pub next_run_at:Option<f64>,pub helper_scripts:Vec<String>,pub file_path:PathBuf}
pub struct FileWorkflowStore{agent_dir:PathBuf,pub library:GlobalWorkflowLibrary,pub enablement:AgentWorkflowEnablement,pub automations:FileAutomationStore}
impl FileWorkflowStore{
 pub fn new(agent_dir:impl Into<PathBuf>,global_dir:impl Into<PathBuf>)->Self{Self::with_user_time_zone_resolver(agent_dir,global_dir,Arc::new(||None))}
 pub fn with_user_time_zone_resolver(agent_dir:impl Into<PathBuf>,global_dir:impl Into<PathBuf>,resolve_user_time_zone:UserTimeZoneResolver)->Self{let agent_dir=agent_dir.into();let v=Self{library:GlobalWorkflowLibrary::new(global_dir),enablement:AgentWorkflowEnablement::new(agent_dir.clone()),automations:FileAutomationStore::with_user_time_zone_resolver(get_agent_automations_dir(&agent_dir),resolve_user_time_zone),agent_dir};v.migrate_legacy_per_agent_workflows();v}
 pub fn get_location(&self)->&Path{self.library.get_location()}
 fn skill_to_workflow(&self,r:GlobalWorkflowRecord)->WorkflowRecord{WorkflowRecord{id:r.id.clone(),name:r.name,description:r.description,body:r.body,trigger:None,source:"workflow".into(),source_ref:r.source_ref,is_enabled_for_agent:self.enablement.is_enabled(&r.id),created_at:r.created_at,last_run_at:None,next_run_at:None,helper_scripts:r.helper_scripts,file_path:r.file_path}}
 fn automation_to_workflow(&self,a:AutomationRecord)->WorkflowRecord{WorkflowRecord{id:a.id,name:a.name,description:String::new(),body:a.prompt,trigger:Some(WorkflowTrigger{schedule:a.schedule,is_enabled:a.is_enabled}),source:"automation".into(),source_ref:None,is_enabled_for_agent:true,created_at:a.created_at,last_run_at:a.last_run_at,next_run_at:a.next_run_at,helper_scripts:Vec::new(),file_path:a.file_path}}
 pub fn list_all(&self)->Vec<WorkflowRecord>{let mut out=self.library.list().into_iter().map(|r|self.skill_to_workflow(r)).collect::<Vec<_>>();out.extend(self.automations.list().into_iter().map(|a|self.automation_to_workflow(a)));out}
 pub fn list(&self)->Vec<WorkflowRecord>{self.list_all().into_iter().filter(|w|w.is_enabled_for_agent||w.source=="automation").collect()}
 pub fn get(&self,id:&str)->Option<WorkflowRecord>{if let Some(r)=self.library.get(id){return Some(self.skill_to_workflow(r));}self.automations.get(id).map(|a|self.automation_to_workflow(a))}
 pub fn create(&self,spec:&WorkflowSpec)->Result<Option<WorkflowRecord>,String>{let name=clamp_workflow_name(&spec.name);if name.is_empty(){return Ok(None);}if let Some(t)=&spec.trigger{let a=self.automations.upsert(&AutomationSpec{name,prompt:spec.body.clone(),trigger:json!({"type":"cron","schedule":t.schedule}),is_enabled:Some(t.is_enabled)},now_ms()).map_err(|e|e.to_string())?;return Ok(a.map(|a|self.automation_to_workflow(a)));}let body=clamp_workflow_body(&spec.body);if body.is_empty(){return Ok(None);}let normalized=WorkflowSpec{name,description:spec.description.clone(),body,trigger:None,source_ref:spec.source_ref.clone()};let Some(record)=self.library.create(&normalized).map_err(|e|e.to_string())?else{return Ok(None);};self.enablement.set_enabled(&record.id,true).map_err(|e|e.to_string())?;Ok(Some(self.skill_to_workflow(record)))}
 pub fn update(&self,id:&str,spec:&WorkflowSpec)->Result<Option<WorkflowRecord>,String>{let Some(current)=self.get(id)else{return Ok(None);};let name=clamp_workflow_name(&spec.name);if name.is_empty(){return Ok(None);}if current.source=="automation"{let schedule=spec.trigger.as_ref().map(|t|t.schedule.clone()).or_else(||current.trigger.as_ref().map(|t|t.schedule.clone())).unwrap_or_default();let enabled=spec.trigger.as_ref().map(|t|t.is_enabled).or_else(||current.trigger.as_ref().map(|t|t.is_enabled)).unwrap_or(true);let u=self.automations.update(id,&AutomationSpec{name,prompt:spec.body.clone(),trigger:json!({"type":"cron","schedule":schedule}),is_enabled:Some(enabled)}).map_err(|e|e.to_string())?;return Ok(u.map(|a|self.automation_to_workflow(a)));}let body=clamp_workflow_body(&spec.body);if body.is_empty(){return Ok(None);}let normalized=WorkflowSpec{name,description:spec.description.clone(),body,trigger:None,source_ref:spec.source_ref.clone().or(current.source_ref)};Ok(self.library.update(id,&normalized).map_err(|e|e.to_string())?.map(|r|self.skill_to_workflow(r)))}
 pub fn set_enabled_for_agent(&self,id:&str,enabled:bool)->Result<Option<WorkflowRecord>,String>{if self.library.get(id).is_none(){return Ok(None);}self.enablement.set_enabled(id,enabled).map_err(|e|e.to_string())?;Ok(self.get(id))}
 pub fn set_trigger_enabled(&self,id:&str,enabled:bool)->Result<Option<WorkflowRecord>,String>{Ok(self.automations.set_enabled(id,enabled).map_err(|e|e.to_string())?.map(|a|self.automation_to_workflow(a)))}
 pub fn remove(&self,id:&str)->Result<bool,String>{if self.library.get(id).is_some(){let _=self.enablement.forget(id).map_err(|e|e.to_string())?;return self.library.remove(id).map_err(|e|e.to_string());}self.automations.remove(id).map_err(|e|e.to_string())}
 pub fn import_markdown(&self,markdown:&str,fallback:Option<&str>)->Result<Option<(String,String)>,String>{let Some(parsed)=parse_workflow_file(markdown)else{return Ok(None);};let name=if parsed.spec.name.is_empty(){derive_name(&parsed.spec.body).or_else(||fallback.map(ToOwned::to_owned)).unwrap_or_default()}else{parsed.spec.name};if name.is_empty()||parsed.spec.body.is_empty(){return Ok(None);}let spec=WorkflowSpec{name,description:parsed.spec.description,body:parsed.spec.body,trigger:None,source_ref:parsed.spec.source_ref};let Some(r)=self.library.create(&spec).map_err(|e|e.to_string())?else{return Ok(None);};self.enablement.set_enabled(&r.id,true).map_err(|e|e.to_string())?;Ok(Some((r.id,r.name)))}
 pub fn import_live_source(&self,source:&str,fallback:Option<&str>)->Result<Option<(String,String)>,String>{let source=source.trim();if source.is_empty(){return Ok(None);}let name=clamp_workflow_name(fallback.unwrap_or_else(||source.rsplit('/').next().unwrap_or("Imported skill")));if name.is_empty(){return Ok(None);}let body=format!("This workflow is a live reference to the skill at {}.\nRead that source now with your file or fetch tools and follow it as written. Do not assume its contents from this note; the source is the source of truth and may have changed since this workflow was created.",source);let spec=WorkflowSpec{name:name.clone(),description:format!("Use when the \"{name}\" skill applies; it is a live reference to {source}."),body,trigger:None,source_ref:Some(source.to_string())};let Some(r)=self.library.create(&spec).map_err(|e|e.to_string())?else{return Ok(None);};self.enablement.set_enabled(&r.id,true).map_err(|e|e.to_string())?;Ok(Some((r.id,r.name)))}
 pub fn migrate_legacy_per_agent_workflows(&self){let legacy=self.agent_dir.join(LEGACY_WORKFLOWS_DIRNAME);let Ok(entries)=fs::read_dir(&legacy)else{return;};let mut enabled=Vec::new();for entry in entries.flatten(){if !entry.file_type().map(|k|k.is_dir()).unwrap_or(false){continue;}let id=entry.file_name().to_string_lossy().into_owned();let folder=entry.path();if !self.library.has(&id){let target=self.library.get_location().join(&id);if fs::create_dir_all(self.library.get_location()).is_ok()&&fs::rename(&folder,&target).is_err(){let Ok(raw)=fs::read_to_string(folder.join(LEGACY_WORKFLOW_FILENAME))else{continue;};let Some(parsed)=parse_workflow_file(&raw)else{continue;};if parsed.spec.body.is_empty(){continue;}let mut spec=parsed.spec;if spec.name.is_empty(){spec.name=id.clone();}let _=self.library.write_at(&id,&spec);}}enabled.push(id);}self.library.rename_legacy_recipe_files();if !enabled.is_empty(){let _=self.enablement.enable_all(&enabled);}let _=fs::remove_dir_all(legacy);}
}
pub fn agent_has_workflows(agent_dir:&Path)->bool{if AgentWorkflowEnablement::new(agent_dir.to_path_buf()).has_explicit_entries(){return true;}let legacy=agent_dir.join(LEGACY_WORKFLOWS_DIRNAME);let Ok(entries)=fs::read_dir(legacy)else{return false;};entries.flatten().any(|e|e.file_type().map(|k|k.is_dir()).unwrap_or(false)&&e.path().join(LEGACY_WORKFLOW_FILENAME).is_file())}
fn derive_name(body:&str)->Option<String>{for raw in body.lines(){let line=raw.trim();if line.is_empty(){continue;}let text=line.trim_start_matches('#').trim().replace(['*','_','>'],"").replace(char::from(96),"");if !text.is_empty(){return Some(text.chars().take(80).collect());}}None}
fn now_ms()->f64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis()as f64}
