use std::collections::BTreeSet;
use std::fs;
use std::io;
use std::path::{Path,PathBuf};
use std::process;
use std::sync::{Arc,Mutex};
use std::time::{SystemTime,UNIX_EPOCH};
use serde_json::{Map,Value};
use crate::storage::folder_id::is_safe_folder_id;

pub const WORKFLOW_FILENAME:&str="SKILL.md";pub const LEGACY_WORKFLOW_FILENAME:&str="workflow.md";pub const WORKFLOW_MAX_NAME_LENGTH:usize=80;pub const WORKFLOW_MAX_DESCRIPTION_LENGTH:usize=1_536;pub const WORKFLOW_MAX_BODY_LENGTH:usize=100_000;pub const WORKFLOW_MAX_PER_AGENT:usize=100;pub const WORKFLOW_CHANGE_DEBOUNCE_MS:u64=50;
pub type WorkflowChangeListener=Arc<dyn Fn()+Send+Sync+'static>;
#[derive(Debug,Clone,PartialEq,Eq)]pub struct WorkflowTrigger{pub schedule:String,pub is_enabled:bool}
#[derive(Debug,Clone,PartialEq)]pub struct WorkflowSpec{pub name:String,pub description:String,pub body:String,pub trigger:Option<WorkflowTrigger>,pub source_ref:Option<String>}
#[derive(Debug,Clone,PartialEq)]pub struct ParsedWorkflow{pub spec:WorkflowSpec,pub data:Map<String,Value>}
#[derive(Debug,Clone,PartialEq)]pub struct GlobalWorkflowRecord{pub id:String,pub name:String,pub description:String,pub body:String,pub suggested_trigger:Option<WorkflowTrigger>,pub source_ref:Option<String>,pub helper_scripts:Vec<String>,pub created_at:f64,pub file_path:PathBuf}

pub fn get_global_workflows_dir(sand_root:&Path)->PathBuf{sand_root.join("workflows")}
pub fn clamp_workflow_name(v:&str)->String{clamp_line(v,WORKFLOW_MAX_NAME_LENGTH)}
pub fn clamp_workflow_description(v:&str)->String{clamp_line(v,WORKFLOW_MAX_DESCRIPTION_LENGTH)}
pub fn clamp_workflow_body(v:&str)->String{v.trim().chars().take(WORKFLOW_MAX_BODY_LENGTH).collect()}
pub fn slugify_workflow_name(name:&str)->String{let mut slug=String::new();let mut dash=false;for c in name.to_ascii_lowercase().chars(){if c.is_ascii_alphanumeric(){slug.push(c);dash=false;}else if !dash&&!slug.is_empty(){slug.push('-');dash=true;}if slug.len()>=64{break;}}while slug.ends_with('-'){slug.pop();}if slug.is_empty(){"workflow".into()}else{slug}}
fn clamp_line(v:&str,max:usize)->String{v.replace(['\r','\n']," ").split_whitespace().collect::<Vec<_>>().join(" ").chars().take(max).collect()}
fn scalar(raw:&str)->Value{let v=raw.trim();match v{"true"=>Value::Bool(true),"false"=>Value::Bool(false),"null"|"~"=>Value::Null,_=>{if let Ok(n)=v.parse::<f64>(){if let Some(n)=serde_json::Number::from_f64(n){return Value::Number(n);}}if v.starts_with('"')&&v.ends_with('"'){if let Ok(p)=serde_json::from_str::<Value>(v){return p;}}if v.starts_with('\'')&&v.ends_with('\''){return Value::String(v[1..v.len()-1].replace("''","'"));}Value::String(v.to_string())}}}
fn insert_nested(root:&mut Map<String,Value>,path:&[String],key:String,value:Value){if path.is_empty(){root.insert(key,value);return;}let entry=root.entry(path[0].clone()).or_insert_with(||Value::Object(Map::new()));if !entry.is_object(){*entry=Value::Object(Map::new());}insert_nested(entry.as_object_mut().unwrap(),&path[1..],key,value);}
fn parse_frontmatter(text:&str)->Map<String,Value>{let mut root=Map::new();let mut stack:Vec<(usize,String)>=Vec::new();for raw in text.lines(){if raw.trim().is_empty()||raw.trim_start().starts_with('#'){continue;}let indent=raw.chars().take_while(|c|c.is_whitespace()).count();let trimmed=raw.trim_start();let Some(colon)=trimmed.find(':')else{continue;};let key=trimmed[..colon].trim();if key.is_empty()||key.starts_with(':'){continue;}while stack.last().is_some_and(|(level,_)|*level>=indent){stack.pop();}let path=stack.iter().map(|(_,key)|key.clone()).collect::<Vec<_>>();let tail=trimmed[colon+1..].trim();if tail.is_empty(){insert_nested(&mut root,&path,key.to_string(),Value::Object(Map::new()));stack.push((indent,key.to_string()));}else{insert_nested(&mut root,&path,key.to_string(),scalar(tail));}}root}
fn split_matter(raw:&str)->(Map<String,Value>,String){if !raw.starts_with("---"){return(Map::new(),raw.to_string());}let Some(line_end)=raw.find('\n')else{return(Map::new(),raw.to_string());};let Some(relative)=raw[line_end..].find("\n---")else{return(Map::new(),raw.to_string());};let close=line_end+relative;let data=parse_frontmatter(&raw[line_end+1..close]);let content=raw[close+4..].trim_start_matches(['\r','\n']).to_string();(data,content)}
fn source_ref_of(data:&Map<String,Value>)->Option<String>{let metadata=data.get("metadata").and_then(Value::as_object);metadata.and_then(|m|m.get("source")).and_then(Value::as_str).or_else(||data.get("source").and_then(Value::as_str)).map(str::trim).filter(|v|!v.is_empty()).map(ToOwned::to_owned)}
fn trigger_of(data:&Map<String,Value>)->Option<WorkflowTrigger>{let trigger=data.get("trigger")?.as_object()?;let schedule=trigger.get("schedule").and_then(Value::as_str).unwrap_or_default().split_whitespace().collect::<Vec<_>>().join(" ");(!schedule.is_empty()).then(||WorkflowTrigger{schedule,is_enabled:trigger.get("enabled").and_then(Value::as_bool)!=Some(false)})}
pub fn parse_workflow_file(raw:&str)->Option<ParsedWorkflow>{let(data,content)=split_matter(raw);let body=clamp_workflow_body(&content);if body.is_empty()&&data.is_empty(){return None;}Some(ParsedWorkflow{spec:WorkflowSpec{name:clamp_workflow_name(data.get("name").and_then(Value::as_str).unwrap_or_default()),description:clamp_workflow_description(data.get("description").and_then(Value::as_str).unwrap_or_default()),trigger:trigger_of(&data),body,source_ref:source_ref_of(&data)},data})}
fn yaml_value(value:&Value)->String{match value{Value::String(v)=>serde_json::to_string(v).unwrap_or_else(|_|"\"\"".into()),Value::Number(v)=>v.to_string(),Value::Bool(v)=>v.to_string(),Value::Null=>"null".into(),other=>serde_json::to_string(other).unwrap_or_else(|_|"null".into())}}
fn emit_yaml(data:&Map<String,Value>,indent:usize,out:&mut Vec<String>){for(key,value)in data{if let Some(object)=value.as_object(){out.push(format!("{}{}:"," ".repeat(indent),key));emit_yaml(object,indent+2,out);}else{out.push(format!("{}{}: {}"," ".repeat(indent),key,yaml_value(value)));}}}
pub fn serialize_workflow_file(spec:&WorkflowSpec,existing:&Map<String,Value>)->String{let mut data=existing.clone();data.insert("name".into(),Value::String(spec.name.clone()));if spec.description.is_empty(){data.remove("description");}else{data.insert("description".into(),Value::String(spec.description.clone()));}let legacy=data.remove("source");let mut metadata=data.get("metadata").and_then(Value::as_object).cloned().unwrap_or_default();let next=match &spec.source_ref{Some(s)=>Some(s.clone()),None=>metadata.get("source").and_then(Value::as_str).map(ToOwned::to_owned).or_else(||legacy.and_then(|v|v.as_str().map(ToOwned::to_owned)))};if let Some(source)=next.filter(|s|!s.is_empty()){metadata.insert("source".into(),Value::String(source));}else{metadata.remove("source");}if metadata.is_empty(){data.remove("metadata");}else{data.insert("metadata".into(),Value::Object(metadata));}if let Some(t)=&spec.trigger{data.insert("trigger".into(),serde_json::json!({"schedule":t.schedule,"enabled":t.is_enabled}));}else{data.remove("trigger");}let mut lines=Vec::new();emit_yaml(&data,0,&mut lines);format!("---\n{}\n---\n{}\n",lines.join("\n"),spec.body.trim())}

pub struct GlobalWorkflowLibrary{library_dir:PathBuf,on_change:Arc<Mutex<Option<WorkflowChangeListener>>>}
impl GlobalWorkflowLibrary{
 pub fn new(library_dir:impl Into<PathBuf>)->Self{let v=Self{library_dir:library_dir.into(),on_change:Arc::new(Mutex::new(None))};v.rename_legacy_recipe_files();v}
 pub fn get_location(&self)->&Path{&self.library_dir} pub fn set_on_change(&self,c:Option<WorkflowChangeListener>){if let Ok(mut slot)=self.on_change.lock(){*slot=c;}}fn notify(&self){if let Some(cb)=self.on_change.lock().ok().and_then(|s|s.as_ref().map(Arc::clone)){cb();}}
 pub fn folder(&self,id:&str)->PathBuf{self.library_dir.join(id)} pub fn path(&self,id:&str)->PathBuf{self.folder(id).join(WORKFLOW_FILENAME)}
 pub fn list_ids(&self)->Vec<String>{let Ok(entries)=fs::read_dir(&self.library_dir)else{return Vec::new();};let mut ids=entries.filter_map(Result::ok).filter_map(|e|{let n=e.file_name().into_string().ok()?;let k=e.file_type().ok()?;(k.is_dir()&&is_safe_folder_id(&n)).then_some(n)}).collect::<Vec<_>>();ids.sort();ids}
 pub fn list_helper_scripts(&self,id:&str)->Vec<String>{let reserved=BTreeSet::from([WORKFLOW_FILENAME,LEGACY_WORKFLOW_FILENAME,"runs.json"]);let Ok(entries)=fs::read_dir(self.folder(id))else{return Vec::new();};let mut out=entries.filter_map(Result::ok).filter_map(|e|{let k=e.file_type().ok()?;let n=e.file_name().into_string().ok()?;(k.is_file()&&!reserved.contains(n.as_str())).then_some(n)}).collect::<Vec<_>>();out.sort();out}
 pub fn get(&self,id:&str)->Option<GlobalWorkflowRecord>{if !is_safe_folder_id(id){return None;}let path=self.path(id);let raw=fs::read_to_string(&path).ok()?;let p=parse_workflow_file(&raw)?;if p.spec.body.is_empty(){return None;}Some(GlobalWorkflowRecord{id:id.to_string(),name:if p.spec.name.is_empty(){id.to_string()}else{p.spec.name},description:p.spec.description,body:p.spec.body,suggested_trigger:p.spec.trigger,source_ref:p.spec.source_ref,helper_scripts:self.list_helper_scripts(id),created_at:file_time_ms(&path),file_path:path})}
 pub fn has(&self,id:&str)->bool{self.get(id).is_some()} pub fn list(&self)->Vec<GlobalWorkflowRecord>{let mut out=self.list_ids().into_iter().filter_map(|id|self.get(&id)).collect::<Vec<_>>();out.sort_by(|a,b|a.created_at.partial_cmp(&b.created_at).unwrap_or(std::cmp::Ordering::Equal));out} pub fn count(&self)->usize{self.list_ids().iter().filter(|id|self.get(id).is_some()).count()}
 pub fn unique_id(&self,name:&str)->String{let base=slugify_workflow_name(name);let existing=self.list_ids().into_iter().collect::<BTreeSet<_>>();if !existing.contains(&base){return base;}for suffix in 2..1000{let c=format!("{base}-{suffix}");if !existing.contains(&c){return c;}}format!("{base}-{}",now_ms()as u64)}
 pub fn create(&self,spec:&WorkflowSpec)->Result<Option<GlobalWorkflowRecord>,io::Error>{let name=clamp_workflow_name(&spec.name);let body=clamp_workflow_body(&spec.body);if name.is_empty()||body.is_empty()||self.count()>=WORKFLOW_MAX_PER_AGENT{return Ok(None);}let normalized=WorkflowSpec{name,description:clamp_workflow_description(&spec.description),body,trigger:None,source_ref:spec.source_ref.clone()};self.write_at(&self.unique_id(&normalized.name),&normalized)}
 pub fn update(&self,id:&str,spec:&WorkflowSpec)->Result<Option<GlobalWorkflowRecord>,io::Error>{if !is_safe_folder_id(id)||self.get(id).is_none(){return Ok(None);}let name=clamp_workflow_name(&spec.name);let body=clamp_workflow_body(&spec.body);if name.is_empty()||body.is_empty(){return Ok(None);}let normalized=WorkflowSpec{name,description:clamp_workflow_description(&spec.description),body,trigger:None,source_ref:spec.source_ref.clone()};self.write_at(id,&normalized)}
 pub fn write_at(&self,id:&str,spec:&WorkflowSpec)->Result<Option<GlobalWorkflowRecord>,io::Error>{if !is_safe_folder_id(id){return Ok(None);}let existing=fs::read_to_string(self.path(id)).ok().and_then(|raw|parse_workflow_file(&raw)).map(|p|p.data).unwrap_or_default();atomic_write(&self.path(id),serialize_workflow_file(spec,&existing).as_bytes())?;self.notify();Ok(self.get(id))}
 pub fn remove(&self,id:&str)->Result<bool,io::Error>{if !is_safe_folder_id(id){return Ok(false);}let folder=self.folder(id);match fs::metadata(&folder){Ok(m)if m.is_dir()=>{},Ok(_)=>return Ok(false),Err(e)if e.kind()==io::ErrorKind::NotFound=>return Ok(false),Err(e)=>return Err(e)}fs::remove_dir_all(folder)?;self.notify();Ok(true)}
 pub fn rename_legacy_recipe_files(&self){for id in self.list_ids(){let legacy=self.folder(&id).join(LEGACY_WORKFLOW_FILENAME);if !legacy.is_file()||self.path(&id).is_file(){continue;}let _=fs::rename(legacy,self.path(&id));}}
}
fn atomic_write(path:&Path,bytes:&[u8])->io::Result<()>{if let Some(parent)=path.parent(){fs::create_dir_all(parent)?;}let n=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos();let tmp=PathBuf::from(format!("{}.{}.{}.tmp",path.display(),process::id(),n));fs::write(&tmp,bytes)?;if let Err(e)=fs::rename(&tmp,path){let _=fs::remove_file(&tmp);return Err(e);}Ok(())}
fn file_time_ms(path:&Path)->f64{fs::metadata(path).ok().and_then(|m|m.created().ok().or_else(||m.modified().ok())).and_then(|t|t.duration_since(UNIX_EPOCH).ok()).map(|d|d.as_millis()as f64).unwrap_or_else(now_ms)}
fn now_ms()->f64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis()as f64}
