#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum HostExtensionId {
    ActionAudit,
    Attachments,
    Auth,
    AutoReview,
    Automations,
    BoxLifecycle,
    BoxStoreSync,
    BrowserUa,
    CloudAgents,
    CodebaseTelemetry,
    ContentSearch,
    CrossUserSharing,
    Experiments,
    ForeverBox,
    HostUpgrade,
    Inference,
    LocalExec,
    LocalToolPermission,
    ManagedSetup,
    Mcp,
    Memory,
    Notifications,
    NotifyBus,
    Secrets,
    Session,
    Settings,
    SourceMap,
    StateBackstop,
    TeachRecording,
    Telemetry,
    Transcript,
    Trays,
    TurnExecution,
    Wallpaper,
    WebauthnProxy,
}

impl HostExtensionId {
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ActionAudit => "action-audit",
            Self::Attachments => "attachments",
            Self::Auth => "auth",
            Self::AutoReview => "auto-review",
            Self::Automations => "automations",
            Self::BoxLifecycle => "box-lifecycle",
            Self::BoxStoreSync => "box-store-sync",
            Self::BrowserUa => "browser-ua",
            Self::CloudAgents => "cloud-agents",
            Self::CodebaseTelemetry => "codebase-telemetry",
            Self::ContentSearch => "content-search",
            Self::CrossUserSharing => "cross-user-sharing",
            Self::Experiments => "experiments",
            Self::ForeverBox => "forever-box",
            Self::HostUpgrade => "host-upgrade",
            Self::Inference => "inference",
            Self::LocalExec => "local-exec",
            Self::LocalToolPermission => "local-tool-permission",
            Self::ManagedSetup => "managed-setup",
            Self::Mcp => "mcp",
            Self::Memory => "memory",
            Self::Notifications => "notifications",
            Self::NotifyBus => "notify-bus",
            Self::Secrets => "secrets",
            Self::Session => "session",
            Self::Settings => "settings",
            Self::SourceMap => "source-map",
            Self::StateBackstop => "state-backstop",
            Self::TeachRecording => "teach-recording",
            Self::Telemetry => "telemetry",
            Self::Transcript => "transcript",
            Self::Trays => "trays",
            Self::TurnExecution => "turn-execution",
            Self::Wallpaper => "wallpaper",
            Self::WebauthnProxy => "webauthn-proxy",
        }
    }

    pub fn parse(value: &str) -> Option<Self> {
        match value {
            "action-audit" => Some(Self::ActionAudit),
            "attachments" => Some(Self::Attachments),
            "auth" => Some(Self::Auth),
            "auto-review" => Some(Self::AutoReview),
            "automations" => Some(Self::Automations),
            "box-lifecycle" => Some(Self::BoxLifecycle),
            "box-store-sync" => Some(Self::BoxStoreSync),
            "browser-ua" => Some(Self::BrowserUa),
            "cloud-agents" => Some(Self::CloudAgents),
            "codebase-telemetry" => Some(Self::CodebaseTelemetry),
            "content-search" => Some(Self::ContentSearch),
            "cross-user-sharing" => Some(Self::CrossUserSharing),
            "experiments" => Some(Self::Experiments),
            "forever-box" => Some(Self::ForeverBox),
            "host-upgrade" => Some(Self::HostUpgrade),
            "inference" => Some(Self::Inference),
            "local-exec" => Some(Self::LocalExec),
            "local-tool-permission" => Some(Self::LocalToolPermission),
            "managed-setup" => Some(Self::ManagedSetup),
            "mcp" => Some(Self::Mcp),
            "memory" => Some(Self::Memory),
            "notifications" => Some(Self::Notifications),
            "notify-bus" => Some(Self::NotifyBus),
            "secrets" => Some(Self::Secrets),
            "session" => Some(Self::Session),
            "settings" => Some(Self::Settings),
            "source-map" => Some(Self::SourceMap),
            "state-backstop" => Some(Self::StateBackstop),
            "teach-recording" => Some(Self::TeachRecording),
            "telemetry" => Some(Self::Telemetry),
            "transcript" => Some(Self::Transcript),
            "trays" => Some(Self::Trays),
            "turn-execution" => Some(Self::TurnExecution),
            "wallpaper" => Some(Self::Wallpaper),
            "webauthn-proxy" => Some(Self::WebauthnProxy),
            _ => None,
        }
    }
}
