use std::collections::BTreeMap;use std::fs;use std::io;use std::path::{Path,PathBuf};use std::process;use std::sync::atomic::{AtomicU64,Ordering};use std::sync::{Arc,Mutex};use std::time::{SystemTime,UNIX_EPOCH};
use chrono_tz::Tz;use serde_json::{Map,Value};use crate::host_paths::get_sand_root_dir;
pub type UserTimeZoneListener=Arc<dyn Fn(Option<String>)+Send+Sync+'static>;pub type SettingsChangeListener=Arc<dyn Fn(Vec<String>)+Send+Sync+'static>;
pub fn is_valid_iana_time_zone(value:&str)->bool{value.parse::<Tz>().is_ok()}

pub const SAND_AUTO_REVIEW_INSTRUCTION_MAX_ENTRIES:usize=20;
pub const SAND_AUTO_REVIEW_INSTRUCTION_MAX_CHARS:usize=1_000;
#[derive(Debug,Clone,PartialEq,Eq)]
pub struct SandAutoReviewInstructions{pub is_enabled:bool,pub allow_instructions:Vec<String>,pub block_instructions:Vec<String>}
impl Default for SandAutoReviewInstructions{fn default()->Self{Self{is_enabled:true,allow_instructions:Vec::new(),block_instructions:Vec::new()}}}
fn normalize_auto_review_instruction_list(raw:Option<&Value>)->Vec<String>{let Some(items)=raw.and_then(Value::as_array)else{return Vec::new();};let mut result=Vec::new();for item in items{let Some(value)=item.as_str()else{continue;};let trimmed=value.trim();if trimmed.is_empty(){continue;}let clamped=trimmed.chars().take(SAND_AUTO_REVIEW_INSTRUCTION_MAX_CHARS).collect::<String>();if !result.contains(&clamped){result.push(clamped);}if result.len()>=SAND_AUTO_REVIEW_INSTRUCTION_MAX_ENTRIES{break;}}result}
pub fn normalize_sand_auto_review_instructions(raw:Option<&Value>)->SandAutoReviewInstructions{let object=raw.and_then(Value::as_object);SandAutoReviewInstructions{is_enabled:object.and_then(|value|value.get("isEnabled")).and_then(Value::as_bool)!=Some(false),allow_instructions:normalize_auto_review_instruction_list(object.and_then(|value|value.get("allowInstructions"))),block_instructions:normalize_auto_review_instruction_list(object.and_then(|value|value.get("blockInstructions")))}}

#[derive(Debug,Clone,Copy,PartialEq,Eq)]
pub enum SandLocalToolPermission{Always,Ask,Never}
pub const SAND_DEFAULT_LOCAL_TOOL_PERMISSION:SandLocalToolPermission=SandLocalToolPermission::Ask;
impl SandLocalToolPermission{
pub const fn as_str(self)->&'static str{match self{Self::Always=>"always",Self::Ask=>"ask",Self::Never=>"never"}}
pub fn parse(value:&str)->Option<Self>{match value{ "always"=>Some(Self::Always),"ask"=>Some(Self::Ask),"never"=>Some(Self::Never),_=>None}}
}
pub fn normalize_sand_local_tool_permission(value:Option<&str>)->SandLocalToolPermission{value.and_then(SandLocalToolPermission::parse).unwrap_or(SAND_DEFAULT_LOCAL_TOOL_PERMISSION)}
pub struct SettingsSubscription<T:?Sized>{id:u64,listeners:Arc<Mutex<BTreeMap<u64,Arc<T>>>>,active:bool}
impl<T:?Sized>SettingsSubscription<T>{pub fn unsubscribe(mut self){if self.active{if let Ok(mut l)=self.listeners.lock(){l.remove(&self.id);}self.active=false;}}}
impl<T:?Sized>Drop for SettingsSubscription<T>{fn drop(&mut self){if self.active{if let Ok(mut l)=self.listeners.lock(){l.remove(&self.id);}self.active=false;}}}
pub struct SettingsService{settings_path:PathBuf,user_time_zone_listeners:Arc<Mutex<BTreeMap<u64,UserTimeZoneListener>>>,change_listeners:Arc<Mutex<BTreeMap<u64,SettingsChangeListener>>>,next_listener_id:AtomicU64}
impl SettingsService{
pub fn production()->Self{Self::new(get_sand_root_dir().join("settings.json"))}
pub fn new(path:impl Into<PathBuf>)->Self{Self{settings_path:path.into(),user_time_zone_listeners:Arc::new(Mutex::new(BTreeMap::new())),change_listeners:Arc::new(Mutex::new(BTreeMap::new())),next_listener_id:AtomicU64::new(1)}}
pub fn get_settings_path(&self)->&Path{&self.settings_path}
fn load(&self)->Map<String,Value>{let Ok(raw)=fs::read_to_string(&self.settings_path)else{return Map::from_iter([("version".into(),Value::from(1))]);};let Ok(Value::Object(mut v))=serde_json::from_str::<Value>(&raw)else{return Map::from_iter([("version".into(),Value::from(1))]);};if v.get("version").and_then(Value::as_i64)!=Some(1){v.clear();v.insert("version".into(),Value::from(1));}v}
fn persist(&self,v:&Map<String,Value>)->io::Result<()>{if let Some(p)=self.settings_path.parent(){fs::create_dir_all(p)?;}let mut raw=serde_json::to_string_pretty(&Value::Object(v.clone())).map_err(io::Error::other)?;raw.push('\n');let n=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos();let tmp=PathBuf::from(format!("{}.{}.{}.tmp",self.settings_path.display(),process::id(),n));fs::write(&tmp,raw)?;if let Err(e)=fs::rename(&tmp,&self.settings_path){let _=fs::remove_file(&tmp);return Err(e);}Ok(())}
pub fn get_detected_user_time_zone(&self)->Option<String>{self.load().get("userTimeZone").and_then(Value::as_str).filter(|v|!v.is_empty()).map(ToOwned::to_owned)}
pub fn get_user_time_zone_override(&self)->Option<String>{self.load().get("userTimeZoneOverride").and_then(Value::as_str).filter(|v|!v.is_empty()).map(ToOwned::to_owned)}
pub fn get_user_time_zone(&self)->Option<String>{self.get_user_time_zone_override().or_else(||self.get_detected_user_time_zone())}
pub fn get_host_settings(&self)->Value{let mut o=Map::new();if let Some(v)=self.get_detected_user_time_zone(){o.insert("userTimeZone".into(),Value::String(v));}if let Some(v)=self.get_user_time_zone_override(){o.insert("userTimeZoneOverride".into(),Value::String(v));}o.insert("localToolPermission".into(),Value::String(self.get_local_tool_permission().as_str().into()));let auto_review=self.get_auto_review_instructions();o.insert("autoReviewInstructions".into(),serde_json::json!({"isEnabled":auto_review.is_enabled,"allowInstructions":auto_review.allow_instructions,"blockInstructions":auto_review.block_instructions}));Value::Object(o)}
pub fn set_user_time_zone(&self,v:Option<&str>)->Result<bool,String>{self.set_zone_field("userTimeZone",v)}
pub fn set_user_time_zone_override(&self,v:Option<&str>)->Result<bool,String>{self.set_zone_field("userTimeZoneOverride",v)}
fn set_zone_field(&self,field:&str,value:Option<&str>)->Result<bool,String>{let trimmed=value.map(str::trim).filter(|v|!v.is_empty());if let Some(z)=trimmed{if !is_valid_iana_time_zone(z){return Ok(false);}}let before=self.get_user_time_zone();let mut s=self.load();let changed=match trimmed{Some(z)=>{if s.get(field).and_then(Value::as_str)==Some(z){false}else{s.insert(field.into(),Value::String(z.into()));true}},None=>s.remove(field).is_some()};if !changed{return Ok(false);}self.persist(&s).map_err(|e|e.to_string())?;let after=self.get_user_time_zone();if after!=before{let ls=self.user_time_zone_listeners.lock().map(|l|l.values().cloned().collect::<Vec<_>>()).unwrap_or_default();for l in ls{l(after.clone());}}let ls=self.change_listeners.lock().map(|l|l.values().cloned().collect::<Vec<_>>()).unwrap_or_default();for l in ls{l(vec![field.to_string()]);}Ok(true)}
pub fn get_auto_review_instructions(&self)->SandAutoReviewInstructions{let settings=self.load();normalize_sand_auto_review_instructions(settings.get("autoReviewInstructions"))}
pub fn set_auto_review_instructions(&self,value:&SandAutoReviewInstructions)->Result<bool,String>{let normalized=SandAutoReviewInstructions{is_enabled:value.is_enabled,allow_instructions:normalize_auto_review_instruction_list(Some(&Value::Array(value.allow_instructions.iter().cloned().map(Value::String).collect()))),block_instructions:normalize_auto_review_instruction_list(Some(&Value::Array(value.block_instructions.iter().cloned().map(Value::String).collect())))};let next=serde_json::json!({"isEnabled":normalized.is_enabled,"allowInstructions":normalized.allow_instructions,"blockInstructions":normalized.block_instructions});let mut settings=self.load();if settings.get("autoReviewInstructions")==Some(&next){return Ok(false);}settings.insert("autoReviewInstructions".into(),next);self.persist(&settings).map_err(|error|error.to_string())?;let listeners=self.change_listeners.lock().map(|listeners|listeners.values().cloned().collect::<Vec<_>>()).unwrap_or_default();for listener in listeners{listener(vec!["autoReviewInstructions".to_string()]);}Ok(true)}
pub fn get_local_tool_permission(&self)->SandLocalToolPermission{normalize_sand_local_tool_permission(self.load().get("localToolPermission").and_then(Value::as_str))}
pub fn set_local_tool_permission(&self,value:SandLocalToolPermission)->Result<bool,String>{let mut s=self.load();if s.get("localToolPermission").and_then(Value::as_str)==Some(value.as_str()){return Ok(false);}s.insert("localToolPermission".into(),Value::String(value.as_str().into()));self.persist(&s).map_err(|e|e.to_string())?;let ls=self.change_listeners.lock().map(|l|l.values().cloned().collect::<Vec<_>>()).unwrap_or_default();for l in ls{l(vec!["localToolPermission".to_string()]);}Ok(true)}
pub fn subscribe_to_user_time_zone(&self,listener:UserTimeZoneListener)->SettingsSubscription<dyn Fn(Option<String>)+Send+Sync+'static>{let id=self.next_listener_id.fetch_add(1,Ordering::Relaxed);self.user_time_zone_listeners.lock().expect("settings timezone listeners poisoned").insert(id,listener);SettingsSubscription{id,listeners:Arc::clone(&self.user_time_zone_listeners),active:true}}
pub fn subscribe_to_changes(&self,listener:SettingsChangeListener)->SettingsSubscription<dyn Fn(Vec<String>)+Send+Sync+'static>{let id=self.next_listener_id.fetch_add(1,Ordering::Relaxed);self.change_listeners.lock().expect("settings change listeners poisoned").insert(id,listener);SettingsSubscription{id,listeners:Arc::clone(&self.change_listeners),active:true}}
}
