use std::fs;use std::io;use std::path::{Path,PathBuf};use std::process;use std::sync::{Arc,Mutex};use std::time::{SystemTime,UNIX_EPOCH};
use serde_json::{Map,Value,json};
use crate::storage::folder_id::is_safe_folder_id;
use super::automation::{AUTOMATION_MAX_PER_AGENT,AUTOMATION_MAX_RUN_HISTORY,AutomationConfig,AutomationRecord,AutomationRun,AutomationSpec,clamp_automation_name,clamp_coalesced_run_ids,clamp_run_detail,create_automation_run_id,describe_trigger,normalize_automation_prompt,slugify_automation_name};
use super::automation_trigger::{parse_stored_trigger,trigger_schedule};
use super::routine_notices::is_routine_notice_id;
pub const AUTOMATIONS_DIRNAME:&str="automations";pub const CONFIG_FILENAME:&str="automation.json";pub const RUNS_FILENAME:&str="runs.json";pub const AUTOMATION_CHANGE_DEBOUNCE_MS:u64=50;
pub type AutomationChangeListener=Arc<dyn Fn()+Send+Sync+'static>;
#[derive(Debug,Clone,PartialEq,Eq)]pub enum AutomationDefinitionInspectionState{AgentMissing,DirMissing,Valid,ConfigsInvalid,DirEmpty}
#[derive(Debug,Clone,PartialEq,Eq)]pub struct AutomationDefinitionInspection{pub state:AutomationDefinitionInspectionState,pub valid_definition_count:usize}
#[derive(Debug,thiserror::Error)]pub enum AutomationStoreError{#[error("automation store io error: {0}")]Io(#[from]io::Error),#[error("automation store json error: {0}")]Json(#[from]serde_json::Error)}
#[derive(Clone)]pub struct FileAutomationStore{automations_dir:PathBuf,on_change:Arc<Mutex<Option<AutomationChangeListener>>>}
impl FileAutomationStore{
 pub fn new(automations_dir:impl Into<PathBuf>)->Self{Self{automations_dir:automations_dir.into(),on_change:Arc::new(Mutex::new(None))}}
 pub fn get_location(&self)->&Path{&self.automations_dir}
 pub fn set_on_change(&self,on_change:Option<AutomationChangeListener>){if let Ok(mut slot)=self.on_change.lock(){*slot=on_change;}}
 fn notify(&self){let cb=self.on_change.lock().ok().and_then(|slot|slot.as_ref().map(Arc::clone));if let Some(cb)=cb{cb();}}
 pub fn config_path(&self,id:&str)->PathBuf{self.automations_dir.join(id).join(CONFIG_FILENAME)}
 pub fn runs_path(&self,id:&str)->PathBuf{self.automations_dir.join(id).join(RUNS_FILENAME)}
 pub fn list_ids(&self)->Vec<String>{let Ok(entries)=fs::read_dir(&self.automations_dir)else{return Vec::new();};let mut ids=entries.filter_map(Result::ok).filter_map(|e|{let k=e.file_type().ok()?;let n=e.file_name().into_string().ok()?;(k.is_dir()&&is_safe_folder_id(&n)).then_some(n)}).collect::<Vec<_>>();ids.sort();ids}
 pub fn read_config(&self,id:&str)->Option<AutomationConfig>{if !is_safe_folder_id(id){return None;}let path=self.config_path(id);let raw=fs::read_to_string(&path).ok()?;parse_stored_config(&raw,file_time_ms(&path))}
 pub fn read_runs(&self,id:&str)->Vec<AutomationRun>{let Ok(raw)=fs::read_to_string(self.runs_path(id))else{return Vec::new();};let Ok(value)=serde_json::from_str::<Value>(&raw)else{return Vec::new();};let Some(items)=value.as_array()else{return Vec::new();};let mut runs=items.iter().filter_map(parse_stored_run).collect::<Vec<_>>();runs.sort_by(|a,b|b.started_at.partial_cmp(&a.started_at).unwrap_or(std::cmp::Ordering::Equal));runs.truncate(AUTOMATION_MAX_RUN_HISTORY);runs}
 pub fn write_config(&self,id:&str,config:&AutomationConfig)->Result<(),AutomationStoreError>{atomic_write(&self.config_path(id),serialize_config(config).as_bytes())?;self.notify();Ok(())}
 pub fn write_runs(&self,id:&str,runs:&[AutomationRun])->Result<(),AutomationStoreError>{let values=runs.iter().map(run_to_json).collect::<Vec<_>>();let mut raw=serde_json::to_string_pretty(&values)?;raw.push('\n');atomic_write(&self.runs_path(id),raw.as_bytes())?;self.notify();Ok(())}
 pub fn to_record(&self,id:&str,c:AutomationConfig)->AutomationRecord{let schedule=trigger_schedule(&c.trigger).unwrap_or_default();AutomationRecord{id:id.to_string(),name:c.name,prompt:c.prompt,trigger_description:describe_trigger(&c.trigger),trigger:c.trigger,is_enabled:c.is_enabled,created_at:c.created_at,last_run_at:c.last_run_at,raised_notices:c.raised_notices,schedule,next_run_at:None,runs:self.read_runs(id),file_path:self.config_path(id)}}
 pub fn list(&self)->Vec<AutomationRecord>{let mut out=self.list_definitions();out.sort_by(|a,b|a.created_at.partial_cmp(&b.created_at).unwrap_or(std::cmp::Ordering::Equal));out}
 pub fn list_definitions(&self)->Vec<AutomationRecord>{let mut out=self.list_ids().into_iter().filter_map(|id|self.read_config(&id).map(|c|self.to_record(&id,c))).collect::<Vec<_>>();out.sort_by(|a,b|a.created_at.partial_cmp(&b.created_at).unwrap_or(std::cmp::Ordering::Equal));out}
 pub fn get(&self,id:&str)->Option<AutomationRecord>{self.read_config(id).map(|c|self.to_record(id,c))}
 pub fn count(&self)->usize{self.list_ids().iter().filter(|id|self.read_config(id).is_some()).count()}
 pub fn unique_id(&self,name:&str)->String{let base=slugify_automation_name(name);let existing=self.list_ids().into_iter().collect::<std::collections::BTreeSet<_>>();if !existing.contains(&base){return base;}for suffix in 2..1000{let c=format!("{base}-{suffix}");if !existing.contains(&c){return c;}}format!("{base}-{}",now_ms() as u64)}
 pub fn upsert(&self,spec:&AutomationSpec,created_at:f64)->Result<Option<AutomationRecord>,AutomationStoreError>{let name=clamp_automation_name(&spec.name);let prompt=normalize_automation_prompt(&spec.prompt);let Some(trigger)=parse_stored_trigger(&spec.trigger)else{return Ok(None);};if name.is_empty()||prompt.is_empty()||self.count()>=AUTOMATION_MAX_PER_AGENT{return Ok(None);}let id=self.unique_id(&name);let c=AutomationConfig{name,prompt,trigger,is_enabled:spec.is_enabled.unwrap_or(true),created_at,last_run_at:None,raised_notices:Vec::new()};self.write_config(&id,&c)?;Ok(Some(self.to_record(&id,c)))}
 pub fn update(&self,id:&str,spec:&AutomationSpec)->Result<Option<AutomationRecord>,AutomationStoreError>{if !is_safe_folder_id(id){return Ok(None);}let Some(current)=self.read_config(id)else{return Ok(None);};let name=clamp_automation_name(&spec.name);let prompt=normalize_automation_prompt(&spec.prompt);let Some(trigger)=parse_stored_trigger(&spec.trigger)else{return Ok(None);};if name.is_empty()||prompt.is_empty(){return Ok(None);}let c=AutomationConfig{name,prompt,trigger,is_enabled:spec.is_enabled.unwrap_or(current.is_enabled),created_at:current.created_at,last_run_at:current.last_run_at,raised_notices:current.raised_notices};self.write_config(id,&c)?;Ok(Some(self.to_record(id,c)))}
 pub fn set_enabled(&self,id:&str,enabled:bool)->Result<Option<AutomationRecord>,AutomationStoreError>{let Some(mut c)=self.read_config(id)else{return Ok(None);};if c.is_enabled!=enabled{c.is_enabled=enabled;self.write_config(id,&c)?;}Ok(Some(self.to_record(id,c)))}
 pub fn mark_notice_raised(&self,id:&str,notice:&str)->Result<Option<AutomationRecord>,AutomationStoreError>{if !is_routine_notice_id(notice){return Ok(None);}let Some(mut c)=self.read_config(id)else{return Ok(None);};if !c.raised_notices.iter().any(|v|v==notice){c.raised_notices.push(notice.to_string());self.write_config(id,&c)?;}Ok(Some(self.to_record(id,c)))}
 pub fn record_run(&self,id:&str,at:f64)->Result<Option<AutomationRecord>,AutomationStoreError>{let Some(mut c)=self.read_config(id)else{return Ok(None);};c.last_run_at=Some(at);self.write_config(id,&c)?;Ok(Some(self.to_record(id,c)))}
 pub fn begin_run(&self,id:&str,trigger:&str,at:f64,event:Option<&str>,run_id:Option<&str>,coalesced:Option<&[String]>)->Result<Option<AutomationRun>,AutomationStoreError>{if self.read_config(id).is_none(){return Ok(None);}let mut runs=self.read_runs(id);let run_id=run_id.map(ToOwned::to_owned).unwrap_or_else(create_automation_run_id);if let Some(found)=runs.iter().find(|r|r.id==run_id){return Ok(Some(found.clone()));}let run=AutomationRun{id:run_id,trigger:match trigger{"manual"|"event"=>trigger.to_string(),_=>"schedule".into()},started_at:at,finished_at:None,status:"running".into(),detail:None,event:clamp_run_detail(event),coalesced_run_ids:clamp_coalesced_run_ids(coalesced)};runs.insert(0,run.clone());runs.truncate(AUTOMATION_MAX_RUN_HISTORY);self.write_runs(id,&runs)?;Ok(Some(run))}
 pub fn finish_run(&self,id:&str,run_id:&str,status:&str,at:f64,detail:Option<&str>)->Result<Option<AutomationRecord>,AutomationStoreError>{let Some(c)=self.read_config(id)else{return Ok(None);};let mut runs=self.read_runs(id);if let Some(run)=runs.iter_mut().find(|r|r.id==run_id){run.finished_at=Some(at);run.status=if status=="error"{"error".into()}else{"ok".into()};run.detail=clamp_run_detail(detail);self.write_runs(id,&runs)?;}Ok(Some(self.to_record(id,c)))}
 pub fn remove(&self,id:&str)->Result<bool,AutomationStoreError>{if !is_safe_folder_id(id){return Ok(false);}let folder=self.automations_dir.join(id);match fs::metadata(&folder){Ok(m)if m.is_dir()=>{},Ok(_)=>return Ok(false),Err(e)if e.kind()==io::ErrorKind::NotFound=>return Ok(false),Err(e)=>return Err(e.into())}fs::remove_dir_all(folder)?;self.notify();Ok(true)}
}
pub fn get_agent_automations_dir(agent_dir:&Path)->PathBuf{agent_dir.join(AUTOMATIONS_DIRNAME)}
pub fn inspect_agent_automation_definitions(agent_dir:&Path)->AutomationDefinitionInspection{let Ok(meta)=fs::metadata(agent_dir)else{return AutomationDefinitionInspection{state:AutomationDefinitionInspectionState::AgentMissing,valid_definition_count:0};};if !meta.is_dir(){return AutomationDefinitionInspection{state:AutomationDefinitionInspectionState::AgentMissing,valid_definition_count:0};}let dir=get_agent_automations_dir(agent_dir);let Ok(entries)=fs::read_dir(&dir)else{return AutomationDefinitionInspection{state:AutomationDefinitionInspectionState::DirMissing,valid_definition_count:0};};let(mut candidate,mut valid)=(0usize,0usize);for entry in entries.flatten(){let name=entry.file_name().to_string_lossy().into_owned();if !entry.file_type().map(|k|k.is_dir()).unwrap_or(false)||!is_safe_folder_id(&name){continue;}candidate+=1;let path=entry.path().join(CONFIG_FILENAME);let Ok(raw)=fs::read_to_string(&path)else{continue;};if parse_stored_config(&raw,file_time_ms(&path)).is_some(){valid+=1;}}let state=if valid>0{AutomationDefinitionInspectionState::Valid}else if candidate>0{AutomationDefinitionInspectionState::ConfigsInvalid}else{AutomationDefinitionInspectionState::DirEmpty};AutomationDefinitionInspection{state,valid_definition_count:valid}}
pub fn agent_has_automations(agent_dir:&Path)->bool{inspect_agent_automation_definitions(agent_dir).valid_definition_count>0}
pub fn parse_stored_config(raw:&str,fallback:f64)->Option<AutomationConfig>{let parsed=serde_json::from_str::<Value>(raw).ok()?;let o=parsed.as_object()?;let name=clamp_automation_name(o.get("name")?.as_str()?);let prompt=normalize_automation_prompt(o.get("prompt")?.as_str()?);let trigger=if let Some(v)=o.get("trigger"){parse_stored_trigger(v)}else{let schedule=o.get("schedule").and_then(Value::as_str).unwrap_or_default().trim();(!schedule.is_empty()).then(||json!({"type":"cron","schedule":schedule}))}?;if name.is_empty()||prompt.is_empty(){return None;}let authored=o.get("createdAt").and_then(Value::as_f64).filter(|v|v.is_finite()).unwrap_or(fallback);let last_run_at=o.get("lastRunAt").and_then(Value::as_f64).filter(|v|v.is_finite());let raised_notices=o.get("raisedNotices").and_then(Value::as_array).map(|values|{let mut out=Vec::new();for value in values{let Some(id)=value.as_str().map(str::trim).filter(|id|!id.is_empty()&&is_routine_notice_id(id))else{continue};if !out.iter().any(|v|v==id){out.push(id.to_string());}}out}).unwrap_or_default();Some(AutomationConfig{name,prompt,trigger,is_enabled:o.get("enabled").and_then(Value::as_bool)!=Some(false),created_at:authored.min(fallback),last_run_at,raised_notices})}
pub fn serialize_config(c:&AutomationConfig)->String{let mut o=Map::new();o.insert("name".into(),Value::String(c.name.clone()));o.insert("prompt".into(),Value::String(c.prompt.clone()));if let Some(schedule)=trigger_schedule(&c.trigger){o.insert("schedule".into(),Value::String(schedule));if c.trigger.get("type").and_then(Value::as_str)!=Some("cron"){o.insert("trigger".into(),c.trigger.clone());}}else{o.insert("trigger".into(),c.trigger.clone());}o.insert("enabled".into(),Value::Bool(c.is_enabled));o.insert("createdAt".into(),number(c.created_at));o.insert("lastRunAt".into(),c.last_run_at.map(number).unwrap_or(Value::Null));if !c.raised_notices.is_empty(){o.insert("raisedNotices".into(),json!(c.raised_notices));}let mut raw=serde_json::to_string_pretty(&Value::Object(o)).unwrap_or_else(|_|"{}".into());raw.push('\n');raw}
pub fn parse_stored_run(value:&Value)->Option<AutomationRun>{let o=value.as_object()?;let id=o.get("id")?.as_str()?.to_string();if id.is_empty(){return None;}let started_at=o.get("startedAt")?.as_f64().filter(|v|v.is_finite())?;let trigger=match o.get("trigger").and_then(Value::as_str){Some("manual")=>"manual",Some("event")=>"event",_=>"schedule"}.to_string();let status=match o.get("status").and_then(Value::as_str){Some("error")=>"error",Some("running")=>"running",_=>"ok"}.to_string();let finished_at=o.get("finishedAt").and_then(Value::as_f64).filter(|v|v.is_finite());let detail=clamp_run_detail(o.get("detail").and_then(Value::as_str));let event=clamp_run_detail(o.get("event").and_then(Value::as_str));let c=o.get("coalescedRunIds").and_then(Value::as_array).map(|v|v.iter().filter_map(Value::as_str).map(ToOwned::to_owned).collect::<Vec<_>>());Some(AutomationRun{id,trigger,started_at,finished_at,status,detail,event,coalesced_run_ids:clamp_coalesced_run_ids(c.as_deref())})}
fn run_to_json(r:&AutomationRun)->Value{let mut o=Map::new();o.insert("id".into(),Value::String(r.id.clone()));o.insert("trigger".into(),Value::String(r.trigger.clone()));o.insert("startedAt".into(),number(r.started_at));o.insert("finishedAt".into(),r.finished_at.map(number).unwrap_or(Value::Null));o.insert("status".into(),Value::String(r.status.clone()));if let Some(v)=&r.detail{o.insert("detail".into(),Value::String(v.clone()));}if let Some(v)=&r.event{o.insert("event".into(),Value::String(v.clone()));}if let Some(v)=&r.coalesced_run_ids{o.insert("coalescedRunIds".into(),json!(v));}Value::Object(o)}
fn atomic_write(path:&Path,bytes:&[u8])->io::Result<()>{if let Some(parent)=path.parent(){fs::create_dir_all(parent)?;}let n=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_nanos();let tmp=PathBuf::from(format!("{}.{}.{}.tmp",path.display(),process::id(),n));fs::write(&tmp,bytes)?;if let Err(e)=fs::rename(&tmp,path){let _=fs::remove_file(&tmp);return Err(e);}Ok(())}
fn file_time_ms(path:&Path)->f64{fs::metadata(path).ok().and_then(|m|m.created().ok().or_else(||m.modified().ok())).and_then(|t|t.duration_since(UNIX_EPOCH).ok()).map(|d|d.as_millis()as f64).unwrap_or_else(now_ms)}
fn now_ms()->f64{SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis()as f64}
fn number(v:f64)->Value{serde_json::Number::from_f64(v).map(Value::Number).unwrap_or(Value::Null)}
