'use strict';

const { defineEdge } = require('./edge-ipc.cjs');

const methods = {
  openExternal: { args: 'object' },
  respondAppAgentSurfaceRequest: { args: 'object' },
  submitFeedback: { args: 'object' },
  getDesktopEnvironment: { args: 'none' },
  getMessagingIdentity: { args: 'object' },
  connectMessagingSignaling: { args: 'object' },
  sendMessagingSignal: { args: 'object' },
  disconnectMessagingSignaling: { args: 'none' },
  getWindowState: { args: 'none' },
  minimizeWindow: { args: 'none' },
  toggleMaximizeWindow: { args: 'none' },
  closeWindow: { args: 'none' },
  resizeWindowWidth: { args: 'object' },
  setTitleBarOverlayTone: { args: 'object' },
  getThemeState: { args: 'none' },
  setThemePreference: { args: 'object' },
  getHardwareAcceleration: { args: 'none' },
  setHardwareAccelerationEnabled: { args: 'object' },
  relaunchDesktop: { args: 'none' },
  getEgressTunnelEnabled: { args: 'none' },
  setEgressTunnelEnabled: { args: 'object' },
  getEgressTunnelStatus: { args: 'none' },
  egressFetch: { args: 'object' },
  getWebauthnProxyEnabled: { args: 'none' },
  setWebauthnProxyEnabled: { args: 'object' },
  getUpdateStatus: { args: 'none' },
  checkForUpdates: { args: 'none' },
  setUpdateTrack: { args: 'object' },
  quitAndInstallUpdate: { args: 'object' },
  setAutoUpdateWhenIdleOptIn: { args: 'object' },
  getComputeMigrationStatus: { args: 'none' },
  markDeepLinksReady: { args: 'none' },
  getOnboardingSeen: { args: 'none' },
  setOnboardingSeen: { args: 'object' },
  getTimeZone: { args: 'none' },
  setTimeZoneOverride: { args: 'object' },
  getAutoReviewInstructions: { args: 'none' },
  setAutoReviewInstructions: { args: 'object' },
  getLocalToolPermission: { args: 'none' },
  getLocalToolPermissionCeiling: { args: 'none' },
  setLocalToolPermission: { args: 'object' },
  recordLocalToolApproval: { args: 'object' },
  clearLocalToolApprovals: { args: 'none' },
  getSidebarCollapsed: { args: 'none' },
  setSidebarCollapsed: { args: 'object' },
  pickAvatarSource: { args: 'none' },
  pickAvatarFile: { args: 'none' },
  generateAgentAvatarImage: { args: 'object' },
  resolveAttachmentMedia: { args: 'object' },
  readAttachmentText: { args: 'object' },
  readAttachmentBytes: { args: 'object' },
  stageAttachmentBytes: { args: 'object' },
  downloadAttachment: { args: 'object' },
  commitStagedAttachments: { args: 'object' },
  discardStagedAttachment: { args: 'object' },
  forceRecreateComputer: { args: 'none' },
  updateComputer: { args: 'object' },
  forceReconnectGateway: { args: 'none' },
  getExperimentsSnapshot: { args: 'none' },
  applyFeatureFlagOverride: { args: 'object' },
  refreshFeatureFlags: { args: 'none' },
  startRpcTraceWindow: { args: 'none' },
  getAgentDefaultModel: { args: 'none' },
  setAgentDefaultModel: { args: 'object' },
  getComputerUseModel: { args: 'none' },
  setComputerUseModel: { args: 'object' },
  getHostPinnedAgents: { args: 'none' },
  setHostPinnedAgents: { args: 'object' },
  getHostSidebarSections: { args: 'none' },
  setHostSidebarSections: { args: 'object' },
  getAvailableModels: { args: 'none' },
  getOfflineAsrStatus: { args: 'none' },
  configureOfflineAsrModel: { args: 'object' },
  downloadOfflineAsrModel: { args: 'object' },
  transcribeAudio: { args: 'object' },
  getAccountAuthStatus: { args: 'none' },
  loginAccount: { args: 'none' },
  cancelAccountLogin: { args: 'none' },
  logoutAccount: { args: 'none' },
  updateAccountName: { args: 'object' },
  getAccountAvatar: { args: 'none' },
  getAccountSync: { args: 'object' },
  getAccountMiniApps: { args: 'none' },
  getAccountBots: { args: 'none' },
  addBotToAccount: { args: 'object' },
  removeBotFromAccount: { args: 'object' },
  addMiniAppToAccount: { args: 'object' },
  removeMiniAppFromAccount: { args: 'object' },
  routeMiniAppInput: { args: 'object' },
  callMiniAppRuntimeTool: { args: 'object' },
  getMiniAppSessionProjection: { args: 'object' },
  getMiniAppEntitlement: { args: 'object' },
  purchaseMiniAppLifetime: { args: 'object' },
  restoreMiniAppPurchases: { args: 'object' },
  getMiniAppBotMessages: { args: 'object' },
  appendMiniAppBotMessages: { args: 'object' },
  getMiniAppCloudStorage: { args: 'object' },
  setMiniAppCloudStorage: { args: 'object' },
  deleteMiniAppCloudStorage: { args: 'object' },
  reconcileAccountMiniApps: { args: 'none' },
  getWeeklyUsage: { args: 'none' },
  getUsageSummary: { args: 'none' },
  getInferenceRouterStatus: { args: 'none' },
  restartInferenceRouter: { args: 'none' },
  getReviewPreferences: { args: 'none' },
  getPrivacyModeEnabled: { args: 'none' },
  getRuntimeAccess: { args: 'none' },
  refreshRuntimeAccess: { args: 'none' },
  invokeAccountDashboardAction: { args: 'object' },
  cancelRuntimeTrial: { args: 'none' },
  reportAgentLoad: { args: 'object' },
  reportAccessBlocked: { args: 'object' },
  reportAgentsUnreachable: { args: 'object' },
  reportRecoveryAction: { args: 'object' },
  reportRebuildLifecycle: { args: 'object' },
  reportReconciliation: { args: 'object' },
  reportComputeVisibility: { args: 'object' },
  reportSendLatency: { args: 'object' },
  reportSendAck: { args: 'object' },
  reportReactionAck: { args: 'object' },
  reportRenderTtfr: { args: 'object' },
  reportRenderStream: { args: 'object' },
  reportRemoteDesktopSession: { args: 'object' },
  reportRemoteDesktopLiveness: { args: 'object' },
  reportOpenComputer: { args: 'object' },
  reportUpdatePrompt: { args: 'object' },
  reportSigninGate: { args: 'object' },
  reportOnboardingStep: { args: 'object' },
  reportClientFailure: { args: 'object' },
  reportHeapMetrics: { args: 'object' },
  noteConversationForDiagnostics: { args: 'object' },
  openCloudAgent: { args: 'object' },
  getCloudAgentInfo: { args: 'object' },
  cancelCloudAgent: { args: 'object' },
  getSharingState: { args: 'object' },
  createRoomFromAgent: { args: 'object' },
  createRoomInvite: { args: 'object' },
  joinSharedRoom: { args: 'object' },
  respondToRoomJoinRequest: { args: 'object' },
  createSharedRoom: { args: 'object' },
  addOwnAgentToSharedRoom: { args: 'object' },
  removeOwnAgentFromSharedRoom: { args: 'object' },
  setSharedRoomTyping: { args: 'object' },
  leaveSharedRoom: { args: 'object' },
  getForeverBoxStatus: { args: 'object' },
  ensureForeverBox: { args: 'object' },
  handBackForeverBox: { args: 'object' },
  getBoxSecretsStatus: { args: 'object' },
  isAgentNetworkEnabled: { args: 'object' },
  getLinkMetadata: { args: 'object' },
  listSecrets: { args: 'none' },
  upsertSecrets: { args: 'object' },
  removeSecrets: { args: 'object' },
  readClientPersistence: { args: 'object' },
  writeClientPersistence: { args: 'object' },
  removeClientPersistence: { args: 'object' },
  listClientPersistenceKeys: { args: 'object' },
  requestDiskSaverAudit: { args: 'none' },
  migrateClientPersistence: { args: 'object' },
  getMcpState: { args: 'none' },
  getEffectivePlugins: { args: 'none' },
  getMcpCatalog: { args: 'none' },
  getMcpTeamPopularity: { args: 'none' },
  getMcpPluginLogo: { args: 'object' },
  installEntry: { args: 'object' },
  updatePluginInstall: { args: 'object' },
  removeMcpServer: { args: 'object' },
  uninstallPlugin: { args: 'object' },
  authenticateMcpServer: { args: 'object' },
  renameMcpAccount: { args: 'object' },
  removeMcpAccount: { args: 'object' },
  setMcpCustomInstructions: { args: 'object' },
  listMcpServerTools: { args: 'object' },
  toggleMcpToolDisabled: { args: 'object' },
  getDeveloperCommerceProfile: { args: 'none' },
  upsertDeveloperCommerceProfile: { args: 'object' },
  listDeveloperCommerceMiniApps: { args: 'none' },
  registerDeveloperCommerceMiniApp: { args: 'object' },
  listDeveloperCommerceProducts: { args: 'object' },
  createDeveloperCommerceProduct: { args: 'object' },
  updateDeveloperCommerceProduct: { args: 'object' },
  syncDeveloperCommerceGoogleProduct: { args: 'object' },
  getDeveloperPayoutOverview: { args: 'none' },
  upsertDeveloperPayoutProfile: { args: 'object' },
  requestDeveloperPayout: { args: 'object' },
  createDeveloperPayoutOnboarding: { args: 'object' },
  devRestart: { args: 'none' },
  getProductionComputeAttachmentStatus: { args: 'none' },
  setProductionComputeAttachmentEnabled: { args: 'object' },
};

const NATIVE_EDGE = defineEdge('native-desktop', methods, [
  'app-agent-surface-request',
  'mcp-auth-completed',
  'focus-agent',
  'cloud-agent-open',
  'shared-room-changed',
  'deep-link',
  'compute-migration',
  'dev-compute-rebuild',
  'open-feedback',
  'open-about',
  'widget-gallery',
  'force-onboarding',
  'account-auth-changed',
  'experiments-changed',
  'window-state',
  'zoom-factor-changed',
  'update-computer-dispatched',
  'offline-asr-progress',
  'open-offline-asr',
  'remote-desktop-user-presence',
  'dev-compute-pull-progress',
  'egress-tunnel-changed',
  'egress-tunnel-status-changed',
  'webauthn-proxy-changed',
  'skip-onboarding',
  'theme-changed',
  'update-status',
  'messaging-call-signal',
  'messaging-call-status',
]);

module.exports = { NATIVE_EDGE };
