'use strict';
const {contextBridge,ipcRenderer}=require('electron');

const events=[
  'agents.changed','agent.changed','message.delta','message.changed','message.done',
  'plugins.changed','workflows.changed','automations.changed','settings.changed','account.changed','experiments.changed','approval.requested','approval.resolved','approval.cancelled'
];
const invoke=(method,args={})=>ipcRenderer.invoke('grok-agent:'+method,args);

contextBridge.exposeInMainWorld('grokAgent',Object.freeze({
  listAgents:()=>invoke('list-agents'),
  createAgent:x=>invoke('create-agent',x),
  renameAgent:x=>invoke('rename-agent',x),
  updateAgent:x=>invoke('update-agent',x),
  setAgentNotifyOnUpdates:x=>invoke('set-agent-notify',x),
  setAgentPinned:x=>invoke('set-agent-pinned',x),
  setAgentUnread:x=>invoke('set-agent-unread',x),
  duplicateAgent:x=>invoke('duplicate-agent',x),
  setGroupMembers:x=>invoke('set-group-members',x),
  setAgentHidden:x=>invoke('set-agent-hidden',x),
  deleteAgent:x=>invoke('delete-agent',x),
  getThread:x=>invoke('get-thread',x),
  sendMessage:x=>invoke('send-message',x),
  respondToWidget:x=>invoke('respond-to-widget',x),
  dismissWidget:x=>invoke('dismiss-widget',x),
  submitSecret:x=>invoke('submit-secret',x),
  reactToMessage:x=>invoke('react-to-message',x),
  searchMessages:x=>invoke('search-messages',x),
  searchMedia:x=>invoke('search-media',x),
  searchLinks:x=>invoke('search-links',x),
  stopAgent:x=>invoke('stop-agent',x),
  listPlugins:()=>invoke('list-plugins'),
  setPluginInstalled:x=>invoke('set-plugin-installed',x),
  setPluginEnabled:x=>invoke('set-plugin-enabled',x),
  getAccountStatus:()=>invoke('get-account-status'),
  loginAccount:()=>invoke('login-account'),
  cancelAccountLogin:()=>invoke('cancel-account-login'),
  logoutAccount:()=>invoke('logout-account'),
  updateAccountName:x=>invoke('update-account-name',x),
  getAccountAvatar:()=>invoke('get-account-avatar'),
  getAgentChannels:x=>invoke('get-agent-channels',x),
  connectChannel:x=>invoke('connect-channel',x),
  disconnectChannel:x=>invoke('disconnect-channel',x),
  refreshChannel:x=>invoke('refresh-channel',x),
  getAsyncTasks:x=>invoke('get-async-tasks',x),
  getRuntimeSettings:()=>invoke('get-runtime-settings'),
  getExperimentsSnapshot:()=>invoke('get-experiments-snapshot'),
  refreshExperiments:()=>invoke('refresh-experiments'),
  applyFeatureFlagOverride:x=>invoke('apply-feature-flag-override',x),
  setLocalToolPermission:x=>invoke('set-local-tool-permission',x),
  setAutoReviewMode:x=>invoke('set-auto-review-mode',x),
  setAutoReviewInstructions:x=>invoke('set-auto-review-instructions',x),
  resolveApproval:x=>invoke('resolve-approval',x),
  listMcpServers:()=>invoke('list-mcp-servers'),
  addMcpServer:x=>invoke('add-mcp-server',x),
  updateMcpServer:x=>invoke('update-mcp-server',x),
  removeMcpServer:x=>invoke('remove-mcp-server',x),
  setMcpServerEnabled:x=>invoke('set-mcp-server-enabled',x),
  getMcpAccountStatus:x=>invoke('get-mcp-account-status',x),
  listMcpAccounts:x=>invoke('list-mcp-accounts',x),
  connectMcpAccount:x=>invoke('connect-mcp-account',x),
  disconnectMcpAccount:x=>invoke('disconnect-mcp-account',x),
  renameMcpAccount:x=>invoke('rename-mcp-account',x),
  removeMcpAccount:x=>invoke('remove-mcp-account',x),
  setMcpActiveAccount:x=>invoke('set-mcp-active-account',x),
  listMcpServerTools:x=>invoke('list-mcp-server-tools',x),
  setMcpToolEnabled:x=>invoke('set-mcp-tool-enabled',x),
  listMarketplacePlugins:()=>invoke('list-marketplace-plugins'),
  installMarketplacePlugin:x=>invoke('install-marketplace-plugin',x),
  uninstallMarketplacePlugin:x=>invoke('uninstall-marketplace-plugin',x),
  listWorkflows:()=>invoke('list-workflows'),
  saveWorkflow:x=>invoke('save-workflow',x),
  deleteWorkflow:x=>invoke('delete-workflow',x),
  setWorkflowEnabled:x=>invoke('set-workflow-enabled',x),
  getAgentAutomations:x=>invoke('get-agent-automations',x),
  createAgentAutomation:x=>invoke('create-agent-automation',x),
  setAgentAutomationEnabled:x=>invoke('set-agent-automation-enabled',x),
  updateAgentAutomation:x=>invoke('update-agent-automation',x),
  deleteAgentAutomation:x=>invoke('delete-agent-automation',x),
  runAgentAutomationNow:x=>invoke('run-agent-automation-now',x),
  pickFile:()=>ipcRenderer.invoke('grok-agent:pick-file'),
  pickAvatarFile:()=>ipcRenderer.invoke('grok-agent:pick-avatar-file'),
  generateAgentAvatarImage:description=>invoke('generate-agent-avatar-image',{description}),
  setAgentAvatarBytes:x=>invoke('set-agent-avatar-bytes',x),
  readAttachment:x=>invoke('read-attachment',x),
  getDesktopInfo:()=>invoke('get-desktop-info'),
  getUpdateStatus:()=>invoke('get-update-status'),
  checkUpdate:()=>invoke('check-update'),
  setUpdateTrack:x=>invoke('set-update-track',x),
  setAutoUpdate:x=>invoke('set-auto-update',x),
  quitAndInstall:()=>invoke('quit-and-install'),
  submitFeedback:x=>invoke('submit-feedback',x),
  getOnboardingSeen:()=>invoke('get-onboarding-seen'),
  setOnboardingSeen:x=>invoke('set-onboarding-seen',x),
  openExternal:x=>invoke('open-external',x),
  onUpdateStatus(listener){if(typeof listener!=='function')return()=>{};const fn=(_e,status)=>listener(status);ipcRenderer.on('grok-agent:update-status',fn);return()=>ipcRenderer.off('grok-agent:update-status',fn)},
  onDeepLink(listener){if(typeof listener!=='function')return()=>{};const fn=(_e,link)=>listener(link);ipcRenderer.on('grok-agent:deep-link',fn);return()=>ipcRenderer.off('grok-agent:deep-link',fn)},
  subscribe(listener){
    if(typeof listener!=='function')return()=>{};
    const handlers=events.map(name=>{
      const fn=(_e,payload)=>listener({type:name,...(payload||{})});
      ipcRenderer.on('grok-agent:event:'+name,fn);return[name,fn];
    });
    return()=>handlers.forEach(([name,fn])=>ipcRenderer.off('grok-agent:event:'+name,fn));
  }
}));
